#!env node
// Generates examples/INDEX.md, a single index page linking to every
// generated example. Run `node examples/build-index.js` after adding a
// new example script to this array to pick it up.
//
// This is the "regenerate everything" entry point: `npm run examples`
// runs every generator script below (in order) and then this one.

const fs = require('fs')
const path = require('path')
const markdown = require('../src/index.js')

const EXAMPLES = [
  {
    file: 'FeatureShowcase.md',
    script: 'feature-showcase.js',
    title: 'Feature Showcase',
    description: 'Every exported function, in one page.',
  },
  {
    file: 'HeadersAndEmphasis.md',
    script: 'headers-and-emphasis.js',
    title: 'Headers & Emphasis',
    description: 'h1-h6, hX, bold, italic, strikethrough, inline/fenced code (with an optional language for syntax highlighting).',
  },
  {
    file: 'ListsExample.md',
    script: 'lists-example.js',
    title: 'Lists',
    description: 'Ordered, unordered, and task lists — including checked task items.',
  },
  {
    file: 'TablesExample.md',
    script: 'tables-example.js',
    title: 'Tables',
    description: 'Table headers and rows, with and without column alignment.',
  },
  {
    file: 'LinksAndMedia.md',
    script: 'links-and-media.js',
    title: 'Links, Images & Miscellaneous',
    description: 'Links, images, anchors, quotes, GitHub alerts, badges, tags, collapsible sections, underline/sub/superscript, hard breaks, mentions, issue refs, emoji, color swatches, math, and comments.',
  },
  {
    file: 'GeoblocksExample.md',
    script: 'geoblocks-example.js',
    title: 'Diagrams: GeoJSON, TopoJSON & Mermaid',
    description: 'Fenced geojson/topojson blocks that GitHub renders as maps, and fenced mermaid blocks that GitHub renders as diagrams.',
  },
  {
    file: 'README.md',
    script: 'index.js',
    title: 'Company Directory (real-world example)',
    description: 'A multi-file report generated from JSON company/interaction data — the most elaborate example in this directory.',
  },
]

let doc = ''
doc += `[${markdown.link('Back to module README', '../README.md')}]\n`
doc += markdown.hr()
doc += markdown.h1('Examples Index')
doc += 'Every example below is generated by running its script against `mr_markdown_builder` — nothing here is written by hand. Regenerate all of them at once with `npm run examples`, or run an individual script (e.g. `node examples/lists-example.js`) to refresh just one.\n'

doc += markdown.tableHeader(['Example', 'Regenerate with', 'Covers']) + '\n' +
  markdown.tableRows(EXAMPLES.map((example) => [
    markdown.link(example.title, `./${example.file}`),
    markdown.ic(`node examples/${example.script}`),
    example.description,
  ]))

const outPath = path.join(__dirname, 'INDEX.md')
fs.writeFileSync(outPath, doc)
console.log(`Wrote ${outPath}`)
