#!env node
// Generates examples/GeoblocksExample.md. Self-contained: run
// `node examples/geoblocks-example.js` from anywhere to regenerate it.

const fs = require('fs')
const path = require('path')
const markdown = require('../src/index.js')

const point = {
  type: 'Feature',
  geometry: { type: 'Point', coordinates: [-117.078046, 32.934771] },
  properties: { name: 'Example location', description: 'A single point on the map.' },
}

const topology = {
  type: 'Topology',
  objects: {
    example: { type: 'GeometryCollection', geometries: [] },
  },
  arcs: [],
}

let doc = ''
doc += `[${markdown.link('Back to examples index', './INDEX.md')}]\n`
doc += markdown.hr()
doc += markdown.h1('GeoJSON & TopoJSON')
doc += 'Generated by `examples/geoblocks-example.js`, covering `geojson` and `topojson`. GitHub renders fenced ```geojson``` blocks as an interactive map automatically.\n'

doc += markdown.h2('geojson()')
doc += markdown.geojson(point)
doc += '\n'

doc += markdown.h2('topojson()')
doc += markdown.topojson(topology)
doc += '\n'

const outPath = path.join(__dirname, 'GeoblocksExample.md')
fs.writeFileSync(outPath, doc)
console.log(`Wrote ${outPath}`)
