#!env node
// Generates examples/ListsExample.md. Self-contained: run
// `node examples/lists-example.js` from anywhere to regenerate it.

const fs = require('fs')
const path = require('path')
const markdown = require('../src/index.js')

let doc = ''
doc += `[${markdown.link('Back to examples index', './INDEX.md')}]\n`
doc += markdown.hr()
doc += markdown.h1('Lists')
doc += 'Generated by `examples/lists-example.js`, covering `ul`, `ol`, and `tl` (task lists), including nesting.\n'

doc += markdown.h2('Unordered (ul)')
doc += markdown.ul(['Coffee', 'Tea', 'Water'])

doc += markdown.h2('Unordered with a callback')
doc += markdown.ul(['coffee', 'tea', 'water'], (item) => item.toUpperCase())

doc += markdown.h2('Ordered (ol)')
doc += markdown.ol(['Preheat the oven', 'Mix the batter', 'Bake for 25 minutes'])

doc += markdown.h2('Task list (tl) with plain strings')
doc += 'Plain strings always render unchecked:\n'
doc += markdown.tl(['Write the proposal', 'Get sign-off', 'Ship it'])

doc += markdown.h2('Task list (tl) with checked items')
doc += 'Pass `{ text, checked }` objects to control each box individually:\n'
doc += markdown.tl([
  { text: 'Write the proposal', checked: true },
  { text: 'Get sign-off', checked: true },
  { text: 'Ship it', checked: false },
])

doc += markdown.h2('Nested lists')
doc += 'There\'s no separate nesting API: embed a rendered `ul()`/`ol()`/`tl()` call inside an item\'s text, and the continuation lines are automatically indented to stay part of that item.\n'
doc += markdown.h3('Unordered inside unordered')
doc += markdown.ul([
  `Hot drinks\n${markdown.ul(['Coffee', 'Tea']).trimEnd()}`,
  `Cold drinks\n${markdown.ul(['Water', 'Iced tea']).trimEnd()}`,
])
doc += markdown.h3('Ordered inside ordered')
doc += markdown.ol([
  `Prep\n${markdown.ol(['Preheat the oven', 'Grease the pan']).trimEnd()}`,
  'Bake for 25 minutes',
])
doc += markdown.h3('Task list inside unordered')
doc += markdown.ul([
  `Launch checklist\n${markdown.tl([{ text: 'Write the proposal', checked: true }, { text: 'Ship it', checked: false }]).trimEnd()}`,
])

const outPath = path.join(__dirname, 'ListsExample.md')
fs.writeFileSync(outPath, doc)
console.log(`Wrote ${outPath}`)
