#!env node
// Generates examples/TablesExample.md. Self-contained: run
// `node examples/tables-example.js` from anywhere to regenerate it.

const fs = require('fs')
const path = require('path')
const markdown = require('../src/index.js')

const rows = [
  ['Coffee', '$4.50', 'Iced or hot'],
  ['Tea', '$3.75', 'Herbal or black'],
  ['Water', '$1.00', 'Still or sparkling'],
]

let doc = ''
doc += `[${markdown.link('Back to examples index', './INDEX.md')}]\n`
doc += markdown.hr()
doc += markdown.h1('Tables')
doc += 'Generated by `examples/tables-example.js`, covering `tableHeader` and `tableRows`, with and without column alignment.\n'

doc += markdown.h2('Default (unaligned) columns')
doc += markdown.tableHeader(['Item', 'Price', 'Notes']) + '\n' + markdown.tableRows(rows)

doc += markdown.h2('Aligned columns')
doc += 'Pass `[\'left\', \'center\', \'right\']` as a second argument to `tableHeader` to align each column.\n'
doc += markdown.tableHeader(['Item', 'Price', 'Notes'], ['left', 'center', 'right']) + '\n' + markdown.tableRows(rows)

const outPath = path.join(__dirname, 'TablesExample.md')
fs.writeFileSync(outPath, doc)
console.log(`Wrote ${outPath}`)
